apiVersion: operator.openshift.io/v1
kind: OpenShiftControllerManager
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  managementState: Managed
